// console.log('Hello from ts');
var myString;
var myNum;
var myBool;
var myVar;
myString = 'Hello World';
myNum = 22;
myBool = true;
myVar = 5;
// let strArr:string[];
// let numArr:number[];
// let boolArr:boolean[];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
console.log(myBool);
console.log(myNum);
console.log(myString);
console.log(myVar);
strArr = ['Hello', 'World'];
numArr = [1, 2, 3];
boolArr = [true, false, true];
console.log(numArr);
console.log(boolArr);
strNumTuple = ['Hello', 23];
console.log(strNumTuple);
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
console.log(myVoid);
